---
- name: Docker installation on Debian Bookworm host
  #hosts: localhost
  hosts: all
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install dependencies for Docker
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Check if Docker GPG key exists
      command: apt-key finger
      register: existing_gpg_key
      changed_when: false
      failed_when: false

    - name: Add GPG key for Docker to apt if it doesn't already exist
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      when: '"Docker Release" not in existing_gpg_key.stdout'

    - name: Add official Docker repo to apt
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: 
          - docker-ce 
          - docker-ce-cli
          - containerd.io
        state: present

    # Create docker group so user can be added to it
    - name: Create docker group
      group:
        name: docker
        state: present

    # add user to docker group
    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
          
    - name: Check to see if Docker is started and enabled 
      service:
        name: docker
        state: started
        enabled: yes

    # everything below was added
    - name: Reset ssh connection to allow user changes to affect ansible user
      meta: reset_connection

    - name: Enable docker.service
      systemd:
        name: docker.service
        daemon_reload: true
        enabled: true
 
    - name: Enable containerd.service
      systemd:
        name: containerd.service
        daemon_reload: true
        enabled: true
