Vagrant.configure("2") do |config|

  # Set up Private Network so vm can access things running on localhost
  config.vm.network :private_network, ip: "192.168.0.0"

  # Disable nfs so no need for root privleges
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Vagrant box
  # https://app.vagrantup.com/boxes/search
  config.vm.box = "debian-sandbox/bookworm64"

  # Ansible integration on `vagrant up` or `vagrant provision`
  config.vm.provision "ansible" do |a|
    a.verbose = "v"
    a.playbook = "provision.yml"
  end

  # KVM provider
  config.vm.provider :libvirt do |l|
    l.driver = "kvm"
  end

end
